version: "1.0"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - uploads:/root/uploads
    restart: always
    environment:
      - PORT=${PORT}
      - DB_DRIVER=${DB_DRIVER}
      - DB_URL=${DB_URL}
volumes:
  uploads:
