version: '1.0'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: always
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - DB_DRIVER=${DB_DRIVER}