version: "1.0"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - uploads:/root/uploads
    restart: always
    environment:
      - PORT=${PORT}
      - DB_DRIVER=${DB_DRIVER}
      - DB_URL=${DB_URL}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - CDN_URL=${CDN_URL}
volumes:
  uploads:
