CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    avatar VARCHAR(255) NOT NULL,
    username VARCHAR(14) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(128) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);